#!/usr/bin/env bash
# This script is displaying "Best School" atmost 10 times with "bad luck" at 4,
# "good luck" at 8.

x="1"

while [ $x -le 10 ]; do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x+1))
done

