#!/usr/bin/env bash
# This script is displaying numerics atmost 20 times with "bad luck from China"
# after "4"; "bad luck from Japan" after "9"; "bad luck from Italy" after "17"

x="1"

while [ $x -le 20 ]; do
	echo $x
	case $x in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	x=$((x+1))
done

