#!/usr/bin/env bash
# This script remaps IPV4 addresses to hostnames
hosts_temp=~/hosts.new
cp /etc/hosts "$hosts_temp"
sed --quiet -i -E 's/(([0-9]+\.?){4}\slocalhost)/# \1/g' "$hosts_temp"
sed --quiet -i -E 's/(([0-9]+\.?){4}\sfacebook)/# \1/g' "$hosts_temp"
echo -e "\n# host modifications\n127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" >> "$hosts_temp"
cp -f "$hosts_temp" /etc/hosts

