#!/usr/bin/env bash
# completely fixes server bugs
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
# restarts the nginx
su nginx -s /bin/bash -c 'service nginx restart'
